engines:
  bandit:
    enabled: true
  duplication:
    config:
      languages:
      - ruby
    enabled: true
  pylint:
    enabled: true
  radon:
    enabled: true
exclude_paths:
- bin
- build
- dist
- htmlcov
- lifeguard_mongodb.egg-info
- tests
- venv
